apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./np-cert-controller.yaml
  - ./np-operator.yaml
  - ./np-webhook.yaml
  - ./grafanadashboard.yaml
