apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-web
  namespace: flux-system
spec:
  hostnames:
  - flux.jnobrega.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal
    namespace: network
    sectionName: websecure
  rules:
  - backendRefs:
    - name: flux-operator
      namespace: flux-system
      port: 9080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
