---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret grist-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        GRIST_OIDC_IDP_ISSUER: "https://auth.${SECRET_DOMAIN}/application/o/grist/"
        GRIST_OIDC_IDP_CLIENT_ID: "{{ .GRIST_OIDC_IDP_CLIENT_ID }}"
        GRIST_OIDC_IDP_CLIENT_SECRET: "{{ .GRIST_OIDC_IDP_CLIENT_SECRET }}"
        GRIST_OIDC_IDP_END_SESSION_ENDPOINT: "https://auth.${SECRET_DOMAIN}/application/o/grist/end-session/"
        GRIST_DEFAULT_EMAIL: "{{ .GRIST_DEFAULT_EMAIL }}"
        GRIST_SESSION_SECRET: "{{ .GRIST_SESSION_SECRET }}"
        GRIST_BOOT_KEY: "{{ .GRIST_BOOT_KEY }}"
        TYPEORM_DATABASE: &dbname grist
        TYPEORM_USERNAME: &dbuser "{{ .TYPEORM_USERNAME }}"
        TYPEORM_PASSWORD: &dbpass "{{ .TYPEORM_PASSWORD }}"
        TYPEORM_HOST: &dbhost ${NFS_SERVER}
        TYPEORM_PORT: "5432"
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /grist/config
    - extract:
        key: /postgres/super-user