apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-charts.yaml
  - enix-charts.yaml
  - kubernetes-sigs-charts.yaml
  - lwolf-charts.yaml
  - mattermost-charts.yaml
  - runix-charts.yaml
  - sonarqube-charts.yaml
