---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sonarqube-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://SonarSource.github.io/helm-chart-sonarqube
  timeout: 3m