apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dragonfly-operator.yaml
  - app-template.yaml
  - gha-runner-scale-set-controller.yaml
  - gha-runner-scale-set.yaml
  - snapshot-controller.yaml
  - volsync.yaml
  - cert-manager.yaml
  - tuppr.yaml
  - openebs.yaml
  - external-secrets.yaml
  - flux-operator.yaml
  - flux-instance.yaml
  - kubelet-csr-approver.yaml
  - reflector.yaml
  - reloader.yaml
  - spegel.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - longhorn.yaml
  - opentelemetry-operator.yaml
  - prometheus-operator-crds.yaml
  - external-dns.yaml
  - tailscale-operator.yaml
  - traefik.yaml
  - authentik.yaml
  - trivy-operator.yaml
  - traefik-crds.yaml
  - weave-gitops.yaml
  - kyverno.yaml
  - kmcp.yaml
  - kmcp-crds.yaml
  - node-problem-detector.yaml
  - grafana.yaml
  - envoy-gateway.yaml