# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr
  namespace: flux-system
spec:
  targetNamespace: system-upgrade
  path: ./k8s/apps/system-upgrade/tuppr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tuppr
      namespace: system-upgrade
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr-upgrades
spec:
  targetNamespace: system-upgrade
  path: ./k8s/apps/system-upgrade/tuppr/upgrade
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true
  wait: false
  interval: 20m
  dependsOn:
    - name: tuppr