---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.jnobrega.com
    gatus.home-operations.com/endpoint: |-
      group: internal
      ui:
        hide-hostname: true
        hide-url: true
      alerts:
        - type: pushover
          send-on-resolved: true
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.jnobrega.com
      io.cilium/lb-ipam-ips: 192.168.1.251
    labels:
      cilium.l2.announce: "true"
  listeners:
    - name: web
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: websecure
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: jnobrega.com-tls
    - name: tcp
      protocol: TCP
      port: 1883
      allowedRoutes:
        namespaces:
          from: All
    - name: tls
      protocol: TLS
      port: 8883
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-internal
spec:
  parentRefs:
    - name: internal
      namespace: network
      sectionName: web
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301