# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-operator
  namespace: flux-system
spec:
  targetNamespace: tekton-operator
  path: ./k8s/apps/tekton-operator/tekton-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tekton-operator
      namespace: tekton-operator
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
