apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: documents
resources:
  - ./namespace.yaml
  - ./paperless/ks.yaml
  - ./stirling-pdf/ks.yaml
components:
  - ../../components/middlewares
  - ../../components/alerts
