# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy
spec:
  targetNamespace: network
  path: ./k8s/apps/network/envoy-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: envoy-gateway
      namespace: network
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateways
spec:
  targetNamespace: network
  dependsOn:
    - name: cilium-resources
      namespace: kube-system
    - name: envoy-certificates
  path: ./k8s/apps/network/envoy-gateway/gateways
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      failed: status.conditions.filter(e, e.type == 'Programmed').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Programmed').all(e, e.status == 'True')
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-certificates
spec:
  targetNamespace: network
  dependsOn:
    - name: envoy
    - name: cert-manager
      namespace: cert-manager
  path: ./k8s/apps/network/envoy-gateway/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  healthCheckExprs:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
