apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./namespace.yaml
  - ./traefik/ks.yaml
  - ./external-dns/ks.yaml
  - ./cloudflared/ks.yaml
  - ./error-pages/ks.yaml
  - ./tailscale/ks.yaml
components:
  - ../../components/middlewares
  - ../../components/alerts
