apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./namespace.yaml
  - ./external-dns/ks.yaml
  - ./cloudflared/ks.yaml
  - ./tailscale/ks.yaml
  - ./envoy-gateway/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder