apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup
resources:
  - ./namespace.yaml
  - ./snapshot-controller/ks.yaml
  - ./postgres/ks.yaml
  - ./volsync/ks.yaml
  - ./akeyless/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder