apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - folder.yaml
replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: GrafanaFolder
        fieldPaths:
          - metadata.name
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: GrafanaFolder
        fieldPaths:
          - spec.title