apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./namespace.yaml
  - ./lldap/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./authentik/ks.yaml
  - ./trivy-operator/ks.yaml
  - ./kyverno/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder
