---
alerting:
  pushover:
    title: Gatus
    application-token: ${PUSHOVER_GATUS_KEY}
    user-key: ${PUSHOVER_USER_KEY}
    priority: 1
    resolved-priority: 0
    default-alert:
      description: "Health Check Failed"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

# Prevent Gatus from reporting endpoints as unhealthy when Gatus itself is unhealthy, you may configure Gatus to periodically check for internet connectivity.
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 60s

# Gatus needs at least one endpoint to start
endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

ui:
  title: Status | Gatus
  dashboard-heading: "Application's Health Dashboard"
  logo: https://avatars.githubusercontent.com/u/49655819?v=4
  link: https://github.com/Jdavid77
  buttons:
    - name: Github
      link: https://github.com/Jdavid77
    - name: "Cluster Live Status"
      link: https://live.jnobrega.com
web:
  port: ${GATUS_WEB_PORT}