apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./minio/ks.yaml
  - ./dragonfly/ks.yaml
  # - ./pgadmin/ks.yaml
  - ./garage/ks.yaml
  - ./postgresus/ks.yaml
  - ./openebs/ks.yaml
