apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./namespace.yaml
  - ./dragonfly/ks.yaml
  # - ./pgadmin/ks.yaml
  - ./garage/ks.yaml
  - ./openebs/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder
