apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-operator
resources:
  - ./namespace-to.yaml
  - ./namespace-tp.yaml
  - ./tekton-operator/ks.yaml
components:
  - ../../components/alerts/alertmanager
