# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./reflector/ks.yaml
  - ./reloader/ks.yaml
  - ./kube-cleanup-operator/ks.yaml
  - ./node-problem-detector/ks.yaml
  - ./cilium/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./spegel/ks.yaml
  - ./tuppr/ks.yaml
