# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  type: alertmanager
  address: http://alertmanager-operated.monitoring.svc.cluster.local:9093/api/v2/alerts/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kustomization-alert
  namespace: flux-system
spec:
  summary: "Kustomization"
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: "*"
    - kind: FluxInstance
      name: "*"
    - kind: GitRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: OCIRepository
      name: "*"
    - kind: ResourceSet
      name: "*"
  providerRef:
    name: alertmanager
