---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarqube
      version: 2025.6.1
      sourceRef:
        kind: HelmRepository
        name: sonarqube-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  uninstall:
    keepHistory: false
  valuesFrom:
    - targetPath: jdbcOverwrite.jdbcUrl
      kind: Secret
      name: sonarqube-db-secret
      valuesKey: POSTGRES_JDBC_URL
    - targetPath: jdbcOverwrite.jdbcUsername
      kind: Secret
      name: sonarqube-db-secret
      valuesKey: POSTGRES_JDBC_USERNAME
    - targetPath: jdbcOverwrite.jdbcPassword
      kind: Secret
      name: sonarqube-db-secret
      valuesKey: POSTGRES_JDBC_PASSWORD

  values:
    deploymentType: 'Deployment'

    image:
      repository: dhi.io/sonarqube
      tag: "25"
      pullPolicy: IfNotPresent
      pullSecrets:
        - name: dockerhub-secret

    containerSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532

    community:
      enabled: true

    httproute:
      enabled: false

    initSysctl:
      enabled: false

    prometheusExporter:
      enabled: true

    prometheusMonitoring:
      podMonitor:
        enabled: true

    postgresql:
      enabled: false

    jdbcOverwrite:
      enable: true

    extraInitContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18.1@sha256:3c54d39f19fdb82ed5b3f286450e4071133cc6025bd0e25856bc2c522f8fc030
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: sonarqube-db-secret

    annotations:
      reloader.stakater.com/auto: 'true'

    monitoringPasscodeSecretName: sonarqube-monitoring-secret
    monitoringPasscodeSecretKey: MONITORING_SECRET

    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 400m
        memory: 2Gi
