# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret sonarqube-db-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: sonarqube
        INIT_POSTGRES_HOST: 192.168.1.84
        INIT_POSTGRES_USER: &user "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &password "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_JDBC_URL: jdbc:postgresql://192.168.1.84/sonarqube
        POSTGRES_JDBC_USERNAME: *user
        POSTGRES_JDBC_PASSWORD: *password

  dataFrom:
    - extract:
        key: /sonarqube/db
    - extract:
        key: /postgres/super-user
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret sonarqube-monitoring-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: /sonarqube/monitoring