# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grist
  namespace: flux-system
spec:
  targetNamespace: automation
  path: ./k8s/apps/automation/grist/app
  dependsOn:
    - name: volsync
    - name: external-secrets-store
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grist
      namespace: automation
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.reason == 'SecretSyncedError')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.reason == 'SecretSynced')
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
