apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - ./namespace.yaml
  - ./external-secrets/ks.yaml
  - ./akeyless/ks.yaml
components:
  - ../../components/alerts/alertmanager