apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./namespace.yaml
  - ./n8n/ks.yaml
  - ./dragonfly/ks.yaml
  - ./grist/ks.yaml
  - ./kmcp/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder