# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app renderercv
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  uninstall:
    keepHistory: false
  values:
    controllers:
      *app :
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/rendercv/rendercv
              tag: v2.6@sha256:96bc75aa2a170174fc22a253aa478671495a99bbf9476fa46d9620a96989306e
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup: *probes
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 50m
            workingDir: /work
            command: ["tail"]
            args: ["-f", "/dev/null"]
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              runAsNonRoot: true
              runAsUser: 999
              runAsGroup: 999
              seccompProfile: {type: RuntimeDefault}
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.108.1@sha256:867b9a9dedd68f1b46e308cad9525e419db7b0ce0c83831f6a350f37ee7ff6fd
            securityContext:
              runAsUser: 0
            args: ["--auth", "none", "--disable-telemetry", "--disable-update-check", "--user-data-dir", "/tmp/.vscode", "--extensions-dir", "/tmp/.vs1ode", "--port", "8081", "/config"]
          nginx:
            image:
              repository: nginxinc/nginx-unprivileged
              tag: stable-alpine@sha256:9b82d21c3b96bb802a84eb65612b579c29045f373467eb1eb50ff891d1363cc7
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              runAsNonRoot: true
              runAsUser: 101
              runAsGroup: 101
              seccompProfile: {type: RuntimeDefault}
    defaultPodOptions:
      automountServiceAccountToken: false
    service:
      code-server:
        controller: *app
        ports:
          http:
            port: &codePort 8081
      nginx:
        controller: *app
        ports:
          http:
            port: &nginxPort 8080
    route:
      code:
        parentRefs:
          - kind: Gateway
            name: internal
            namespace: network
            sectionName: websecure
        hostnames:
          - code-cv.jnobrega.com
        rules:
          - backendRefs:
              - name: renderercv-code-server
                port: *codePort
      nginx:
        parentRefs:
          - kind: Gateway
            name: external
            namespace: network
            sectionName: websecure
        hostnames:
          - cv.jnobrega.com
        rules:
          - backendRefs:
              - name: renderercv-nginx
                port: *nginxPort
    persistence:
      nginx:
        enabled: true
        type: configMap
        name: nginx-config
        advancedMounts:
          *app :
            nginx:
              - path: /etc/nginx/conf.d/default.conf
                subPath: default.conf
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          *app :
            app:
              - path: /work
            code-server:
              - path: /config
            nginx:
              - path: /work/cv.pdf
                subPath: cv.pdf
      temp:
        enabled: true
        type: emptyDir
        advancedMounts:
          *app :
            code-server:
              - path: /tmp/.vscode
