apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app renderercv-secret
spec:
  refreshInterval: "5m"
  target:
    name: *app
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: cv
        password: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: "password-gen"