apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./weave/ks.yaml
  - ./flux-operator/ks.yaml
  - ./addons/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder