# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage
  namespace: flux-system
spec:
  targetNamespace: storage
  dependsOn:
    - name: external-secrets-store
  path: ./k8s/apps/storage/garage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage-ui
  namespace: flux-system
spec:
  targetNamespace: storage
  dependsOn:
    - name: garage
  path: ./k8s/apps/storage/garage/ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
