apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./namespace.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./metrics-server/ks.yaml
  - ./grafana-operator/ks.yaml
  - ./pihole-exporter/ks.yaml
  - ./loki/ks.yaml
  - ./opentelemetry/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./watch-your-lan/ks.yaml
  - ./gatus/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder