# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kmcp-crds
  namespace: flux-system
spec:
  targetNamespace: automation
  path: ./k8s/apps/automation/kmcp/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kmcp-crds
      namespace: automation
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kmcp
  namespace: flux-system
spec:
  targetNamespace: automation
  path: ./k8s/apps/automation/kmcp/app
  prune: true
  dependsOn:
    - name: kmcp-crds
  sourceRef:
    kind: GitRepository
    name: home-cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kmcp
      namespace: automation
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m