apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ./namespace.yaml
  - ./longhorn/ks.yaml
components:
  - ../../components/alerts/alertmanager
  - ../../components/grafana/folder