apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ./namespace.yaml
  # - ./cloudnative-pg/ks.yaml
  # - ./minio/ks.yaml
  # - ./csi-driver-nfs/ks.yaml
  - ./longhorn/ks.yaml
components:
  - ../../components/alerts